# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"linear_function_dataset": "00_dl_101_pytorch_fastai.ipynb",
         "LinRegModel": "00_dl_101_pytorch_fastai.ipynb",
         "train": "00_dl_101_pytorch_fastai.ipynb",
         "validate": "00_dl_101_pytorch_fastai.ipynb",
         "nonlinear_function_dataset": "00_dl_101_pytorch_fastai.ipynb",
         "MLP3": "00_dl_101_pytorch_fastai.ipynb",
         "show_TensorFunction1D": "utils.ipynb"}

modules = ["dl_101.py",
           "utils.py"]

doc_url = "https://stardust-r.github.io/walk-with-deep-learning/"

git_url = "https://github.com/stardust-r/wwdl/tree/main/"

def custom_doc_links(name): return None
